export const GET_NOTIFICATIONS_REQUEST = 'app/notifications/GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'app/notifications/GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'app/notifications/GET_NOTIFICATIONS_FAILURE';