/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eb383e53-cf9b-4c8a-a30c-decbb4413f36",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KMvEcqENe",
    "aws_user_pools_web_client_id": "66mg7cn8kp9f1dfntljbt0e76g",
    "oauth": {}
};


export default awsmobile;
