const tables = {
  'demoDataSchema': ["X1Dup", "X1", "LocalTime", "Author", "cumulative_authorFreq", "global_authorFreq",
    "sysomosAuthority", "friendsCount", "followersCount", "statuses_count",
    "ff_ratio", "account_created_at", "Language", "Country", "State",
    "City", "Location", "Bio", "accountAge_days", "postsPerDay", "friendsPerDay",
    "followersPerDay", "is_reply", "replyAuthor", "cumulative_replyAuthorFreq",
    "global_replyAuthorFreq", "is_retweet", "retweetAuthor", "cumulative_retweetAuthorFreq",
    "global_retweetAuthorFreq", "is_quote", "quoteAuthor", "cumulative_quoteAuthorFreq",
    "global_quoteAuthorFreq", "is_originalContent", "Contents", "hashtagsCount",
    "mentionsCount", "dateTime_EST", "dateTime_UTC", "year", "month", "day", "hour",
    "minute", "second", "dateDay", "dateHour", "dateMinute", "dateSecond", "statusId",
    "topic", "trendPosition", "trendVolume", "is_trending", "is_promoted", "query",
    "curveId", "ipiThreshold_mins", "userDebut", "cumulative_users", "cumulative_records",
    "cumulative_pDiv", "epochTime", "normTime_secs", "seconds_since_last_post", "cascadeId",
    "manipulation_score", "blockNumber", "start_index", "end_index", "score", "blockSize",
    "overlap", "brigading_detected", "hashtagSPAM_detected", "mentionSPAM_detected",
    "highPostActivity_detected", "highFriendActivity_detected", "coordinationActivity_detected",
    "median_ff_ratio", "iqr_ff_ratio", "mean_new_users", "median_friendsPerDay",
    "median_postsPerDay", "median_global_authorFreq", "mean_hashtagsCount",
    "mean_mentionsCount", "max_followersCount", "min_normTime_secs", "max_normTime_secs",
    "min_epochTime", "max_epochTime", "cnn_activity_label", "ivysys_activity_label"
  ],
  'demoCSVSchema': ["", "X1", "LocalTime", "Author ID", "cumulative_authorFreq", "global_authorFreq",
    "sysomosAuthority", "friendsCount", "followersCount", "statuses_count",
    "ff_ratio", "account_created_at", "Language", "Country", "Province/State",
    "City", "Location", "Bio", "accountAge_days", "postsPerDay", "friendsPerDay",
    "followersPerDay", "is_reply", "replyAuthor", "cumulative_replyAuthorFreq",
    "global_replyAuthorFreq", "is_retweet", "retweetAuthor", "cumulative_retweetAuthorFreq",
    "global_retweetAuthorFreq", "is_quote", "quoteAuthor", "cumulative_quoteAuthorFreq",
    "global_quoteAuthorFreq", "is_originalContent", "Contents", "hashtagsCount",
    "mentionsCount", "dateTime_EST", "dateTime_UTC", "year", "month", "day", "hour",
    "minute", "second", "dateDay", "dateHour", "dateMinute", "dateSecond", "statusId",
    "topic", "trendPosition", "trendVolume", "is_trending", "is_promoted", "query",
    "curveId", "ipiThreshold_mins", "userDebut", "cumulative_users", "cumulative_records",
    "cumulative_pDiv", "epochTime", "normTime_secs", "seconds_since_last_post", "cascadeId",
    "manipulation_score", "blockNumber", "start_index", "end_index", "score", "blockSize",
    "overlap", "brigading_detected", "hashtagSPAM_detected", "mentionSPAM_detected",
    "highPostActivity_detected", "highFriendActivity_detected", "coordinationActivity_detected",
    "median_ff_ratio", "iqr_ff_ratio", "mean_new_users", "median_friendsPerDay",
    "median_postsPerDay", "median_global_authorFreq", "mean_hashtagsCount",
    "mean_mentionsCount", "max_followersCount", "min_normTime_secs", "max_normTime_secs",
    "min_epochTime", "max_epochTime", "cnn_activity_label", "ivysys_activity_label"
  ]
};

export default tables;
